---
title: "Account Returns"
author: "Tim Trice"
date: "2019-03-07"
output: workflowr::wflow_html
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  echo = TRUE, 
  message = TRUE, 
  warning = TRUE, 
  error = FALSE
)
```

```{r libraries, message = FALSE, warning = FALSE}
library(blotter)
library(purrr)
```

```{r sources}
source(here::here("./code/02_settings.R"))
source(here::here("./code/03_functions.R"))
```

```{r data}
load_data()
```

## Account Returns {.tabset}

### Strategy Portfolio

```{r account-returns-portfolio, fig.width = 10, fig.asp = 0.75, dpi = 150}
plot(AcctReturns(Account = account, Portfolios = portfolio))
```

### Theoretical Portfolio

```{r account-returns-theo-portfolio, fig.width = 10, fig.asp = 0.75, dpi = 150}
plot(AcctReturns(Account = account, Portfolios = theo_portfolio))
```

### Benchmark Portfolio

```{r account-returns-benchmark-portfolio, fig.width = 10, fig.asp = 0.75, dpi = 150}
plot(AcctReturns(Account = account, Portfolios = benchmark_portfolio))
```
